=== Foshie/Classes/CMSC420 - MeeshQuest/MeeshQuest/part3in.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Modified the following 04-12-12 wendtm
   - removed treeTypes "plus" and "star"
   - changed VSTrie to HexTrie
  -->

  <!-- definition of simple elements -->
  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="red"/>
      <xs:enumeration value="green"/>
      <xs:enumeration value="blue"/>
      <xs:enumeration value="yellow"/>
      <xs:enumeration value="purple"/>
      <xs:enumeration value="orange"/>
      <xs:enumeration value="black"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sortType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="name"/>
      <xs:enumeration value="coordinate"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cityName">
    <xs:restriction base="xs:string">
      <xs:pattern value="[_a-zA-Z][_a-zA-Z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of attributes -->
  <xs:attributeGroup name="commandAtts">
  	<xs:attribute name="spatialWidth" type="xs:integer"
  		use="required" />
  	<xs:attribute name="spatialHeight" type="xs:integer"
  		use="required" />
  	<xs:attribute name="pmOrder" use="required">
  		<xs:simpleType>
  			<xs:restriction base="xs:positiveInteger">
  				<xs:minInclusive value="1" />
  				<xs:maxInclusive value="3" />
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  	<xs:attribute name="trieOrder" type="xs:positiveInteger"
  		use="optional" />
  	<xs:attribute name="leafOrder" type="xs:positiveInteger"
  		use="required" />
  	<xs:attribute name="type" type="treeTypes" use="optional" />
  </xs:attributeGroup>

  <!-- definition of complex types -->
  <xs:complexType name="emptyCommandType">
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="nameType">
    <xs:attribute name="name" type="cityName" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="cityType">
    <xs:attribute name="name" type="cityName" use="required"/>
    <xs:attribute name="x" type="xs:integer" use="required"/>
    <xs:attribute name="y" type="xs:integer" use="required"/>
    <xs:attribute name="radius" type="xs:integer" use="required"/>
    <xs:attribute name="color" type="colorType" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="roadType">
    <xs:attribute name="start" type="cityName" use="required"/>
    <xs:attribute name="end" type="cityName" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="listType">
    <xs:attribute name="sortBy" type="sortType" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="printIsolatedCityType">
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="nearestType">
    <xs:attribute name="x" type="xs:integer" use="required"/>
    <xs:attribute name="y" type="xs:integer" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="rangeType">
    <xs:attribute name="x" type="xs:integer" use="required"/>
    <xs:attribute name="y" type="xs:integer" use="required"/>
    <xs:attribute name="radius" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="saveMap" type="xs:NCName" use="optional"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="saveMapType">
    <xs:attribute name="name" type="xs:NCName" use="required"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="shortestPathType">
    <xs:attribute name="start" type="cityName" use="required"/>
    <xs:attribute name="end" type="cityName" use="required"/>
    <xs:attribute name="saveMap" type="xs:NCName" use="optional"/>
    <xs:attribute name="saveHTML" type="xs:NCName" use="optional"/>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <!-- definition of elements -->
  <xs:element name="commands">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="createCity" type="cityType"/>
          <xs:element name="deleteCity" type="nameType"/>
          <xs:element name="clearAll" type="emptyCommandType"/>
          <xs:element name="listCities" type="listType"/>
          <xs:element name="printIsolatedCities" type="printIsolatedCityType"/>
          <xs:element name="mapRoad" type="roadType"/>
          <xs:element name="unmapRoad" type="roadType"/>
          <xs:element name="printPMQuadtree" type="emptyCommandType"/>
          <xs:element name="printHexTrie" type="emptyCommandType"/>
          <xs:element name="rangeCities" type="rangeType"/>
          <xs:element name="rangeRoads" type="rangeType"/>
          <xs:element name="nearestCity" type="nearestType"/>
          <xs:element name="nearestIsolatedCity" type="nearestType"/>
          <xs:element name="nearestRoad" type="nearestType"/>
          <xs:element name="nearestCityToRoad" type="roadType"/>
          <xs:element name="shortestPath" type="shortestPathType"/>
          <xs:element name="nameRange" type="roadType"/>
          <xs:element name="saveMap" type="saveMapType"/>
        </xs:choice>
      </xs:sequence>
      <xs:attributeGroup ref="commandAtts"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="treeTypes">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="Bplus"></xs:enumeration>
  		<xs:enumeration value="Bstar"></xs:enumeration>
  	</xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Foshie/Classes/CMSC420 - MeeshQuest/MeeshQuest/src/cmsc420/in.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part3in.xsd"
pmOrder="3" leafOrder="6" type="Bstar" spatialWidth="1024" spatialHeight="1024">

 <createCity id="1"  name="AA1" y="39" x="76" radius="30" color="black"/>
 <printHexTrie id="2"  />
 <createCity id="3"  name="A2" x="81" y="47" radius="35"  color="black"/>
 <printHexTrie id="4"  />
 <createCity id="5"  name="AA3" x="84" y="33" radius="40"  color="black"/>
 <printHexTrie id="6"  />
 <createCity id="7"  name="A4" x="118" y="33" radius="80"  color="black"/>
 <printHexTrie id="8"  />
 <createCity id="9"  name="AA5" x="80" y="25" radius="30"  color="black"/>
 <printHexTrie id="10"  />
 <createCity id="11"  name="A6" x="71" y="42" radius="50"  color="black"/>
 <printHexTrie id="12"  />
 <createCity id="13"  name="AA7" x="2" y="48" radius="10" color="black"/>
 <printHexTrie id="14"  />
 <createCity id="15"  name="AA8" x="13" y="52" radius="10" color="black"/>
 <printHexTrie id="16"  />
 <createCity id="17"  name="A9" x="3" y="40" radius="10" color="black"/>
 <printHexTrie id="18"  />
 <createCity id="19"  name="AA10" x="2" y="41" radius="10" color="black"/>
 <printHexTrie id="20"  />
 <createCity id="21"  name="A11" x="12" y="41" radius="10" color="black"/>
 <printHexTrie id="22"  />
 <createCity id="23"  name="AA12" x="23" y="37" radius="10" color="black"/>
 <printHexTrie id="24"  />
 <createCity id="25"  name="A13" x="28" y="41" radius="10" color="black"/>
 <printHexTrie id="26"  />
 <createCity id="27"  name="AA14" x="18" y="59" radius="10" color="black"/>
 <printHexTrie id="28"  />
 <createCity id="29"  name="A15" x="15" y="400" radius="10" color="black" />
 <printHexTrie id="30"  />
 <createCity id="31"  name="AA16" x="369" y="6" radius="10" color="black" />
 <printHexTrie id="32"  />
 <createCity id="33"  name="A17" x="542" y="550" radius="10" color="black" />
 <printHexTrie id="34"  />
 <createCity id="35" name="ZZ1" x="500" y="500" radius="10" color="black" />
 <printHexTrie id="36"  />
 <createCity id="37" name="Z2" x="1000" y="1000" radius="10" color="black" />
 <printHexTrie id="38"  />
 <createCity id="39" name="ZZ3" x="35" y="134" radius="10" color="black" />
 <printHexTrie id="40"  />
 <createCity id="41" name="Z4" x="129" y="200" radius="10" color="black" />
 <printHexTrie id="42"  />
 <createCity id="43" name="ZZ5" x="600" y="15" radius="10" color="black" />
 <printHexTrie id="44"  />
 <createCity id="45" name="B1" x="700" y="120" radius="10" color="black" />
 <printHexTrie id="46"  />
 <createCity id="47" name="BB2" x="350" y="116" radius="10" color="black" />
 <printHexTrie id="48"  />
 <createCity id="49" name="B3" x="111" y="566" radius="10" color="black" />
 <printHexTrie id="50"  />
 <createCity id="51" name="BB4" x="988" y="988" radius="10" color="black" />
 <printHexTrie id="52"  />
 <createCity id="53" name="B5" x="20" y="43" radius="10" color="black" />
 <printHexTrie id="54"  />
 <createCity id="55" name="BB6" x="144" y="203" radius="10" color="black" />
 <printHexTrie id="56"  />
 <createCity id="57" name="B7" x="375" y="425" radius="10" color="black" />
 <printHexTrie id="58" />
 <clearAll id="59" />
</commands>

=== Foshie/Classes/CMSC420 - MeeshQuest/MeeshQuest/src/cmsc420/part3_public/part3.primary.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part3in.xsd"
 	spatialWidth="512"
 	spatialHeight="512"
 	pmOrder="3" trieOrder="255" 
 	leafOrder="1">
 <createCity id="1" name="Baltimore" y="39" x="76" radius="30" color="black"/>
 <createCity id="2" name="Chicago" x="81" y="47" radius="35"  color="black"/>
 <createCity id="3" name="Atlanta" x="84" y="33" radius="40"  color="black"/>
 <createCity id="4" name="Los_Angeles" x="118" y="33" radius="80"  color="black"/>
 <createCity id="5" name="Miami" x="80" y="25" radius="30"  color="black"/>
 <createCity id="6" name="Boston" x="71" y="42" radius="50"  color="black"/>
 <listCities id="7" sortBy="coordinate"/>
</commands>

=== Foshie/Classes/CMSC420 - MeeshQuest/MeeshQuest/src/cmsc420/part3_public/hexTrieTestPublic.input.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part3in.xsd"
	pmOrder="3" leafOrder="2" spatialWidth="1024" spatialHeight="1024">

 <createCity id="1"  name="Baltimore" y="37" x="140" radius="5" color="black"/>
 <printHexTrie id="2"  />
 <createCity id="3"  name="Chicago" x="133" y="34" radius="5"  color="black"/>
 <printHexTrie id="4"  />
 <createCity id="5"  name="NewYork" x="200" y="300" radius="5" color="black"/>
 <printHexTrie id="6" />
 <createCity id="7"  name="Zurich"  x="1000" y="1000" radius="5" color="black"/>
 <printHexTrie id="8" />
 <createCity id="9"  name="Paris"  x="500" y="400" radius="5" color="black"/>
 <printHexTrie id="10" />
 <createCity id="11" name="Amsterdam" x="450" y="450" radius="5" color="black"/>
 <printHexTrie id="12" />
 <clearAll id="13"  />
</commands>

=== Foshie/Classes/CMSC420 - MeeshQuest/MeeshQuest/src/cmsc420/Archive (1)/in.xml
<commands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="part3in.xsd" spatialWidth="128" spatialHeight="128" pmOrder="2" leafOrder="8">
<createCity id="1" name="city0" x="6" y="70" radius="0" color="black"/>
<createCity id="1" name="city1" x="68" y="70" radius="0" color="black"/>
<mapRoad id="1" start="city0" end="city1"/>
<printPMQuadtree id="1"/>
<saveMap id="1" name="pm2output1"/>
<createCity id="1" name="city2" x="68" y="5" radius="0" color="black"/>
<mapRoad id="1" start="city1" end="city2"/>
<printPMQuadtree id="1"/>
<saveMap id="1" name="pm2output2"/>
<mapRoad id="1" start="city0" end="city2"/>
<printPMQuadtree id="1"/>
<saveMap id="1" name="pm2output3"/>
<createCity id="1" name="city3" x="6" y="5" radius="0" color="black"/>
<mapRoad id="1" start="city0" end="city3"/>
<printPMQuadtree id="1"/>
<saveMap id="1" name="pm2output4"/>
<clearAll id="1"/>
<createCity id="1" name="city0" x="6" y="100" radius="0" color="black"/>
<createCity id="1" name="city1" x="68" y="100" radius="0" color="black"/>
<createCity id="1" name="city2" x="12" y="75" radius="0" color="black"/>
<createCity id="1" name="city3" x="24" y="75" radius="0" color="black"/>
<createCity id="1" name="city4" x="68" y="5" radius="0" color="black"/>
<createCity id="1" name="city5" x="6" y="5" radius="0" color="black"/>
<mapRoad id="1" start="city0" end="city1"/>
<mapRoad id="1" start="city0" end="city5"/>
<mapRoad id="1" start="city2" end="city3"/>
<mapRoad id="1" start="city3" end="city4"/>
<printPMQuadtree id="1"/>
<saveMap id="1" name="pm2output5"/>
</commands>
